version: '3.4'

networks:
  backend:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

  redis:
    image: redis:6.0.7
    container_name: redis
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - backend

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - 8002:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - backend

volumes:
  pgdata:
  elasticsearch-data:
  redis_volume_data:
  redis_insight_volume_data:
