import type { Metadata } from 'next'
import './globals.css'
import { ThemeModeScript } from 'flowbite-react'

export const metadata: Metadata = {
  title: 'Lisence auction',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <ThemeModeScript />
      </head>
      <body>{children}</body>
    </html>
  )
}
