import type { Metadata } from 'next'
import './globals.css'
import { ThemeModeScript } from 'flowbite-react'
import AppHeader from './components/AppHeader'
import AppBanner from './components/AppBanner'

export const metadata: Metadata = {
  title: 'Lisence auction',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <AppHeader />
        <AppBanner />
        <main className='container mx-auto px-5 pt-10'>{children}</main>
      </body>
    </html>
  )
}
